sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .

script:
  - docker run green --name cont /bin/sh -c "ant; ant test;"
  - docker ps -a
  - sudo docker ps -aqf "name=cont"
  - docker logs -f cont
  # - docker container logs -f green:latest
