sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .

script:
  - docker run green -v /var/log/apache2 -P -d "ant; ant test;"
  - docker ps -a
  # - docker container logs -f green:latest
