sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .

script:
  - docker run green -c "ant; ant test;"
  - docker ps -a
  - docker logs green/*
  # - docker container logs -f green:latest
