sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .
  - docker run green /bin/sh -c "ant"
  - docker ps -a

script:
  - docker run green /bin/sh -c "ant test"
