sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .

script:
  - docker run green /var/log/apache2 -c "ant; ant test;"
  - docker ps -a
  # - docker container logs -f green:latest
