sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .
  - docker container logs -f green

script:
  - docker run green /bin/sh -c "ant; ant test;"
  - docker ps -a
