sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .

script:
  - docker run -d --name cont green /bin/sh -c "ant; ant test"
  - sudo docker ps -aqf "name=cont"
  - docker logs -f cont
  - docker container logs -f cont
