sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .

script:
  - docker run green /bin/sh -c "ant; ant test;"
  - docker ps -a
  - sudo docker ps -aqf "name=green"
  # - docker logs green/*
  # - docker container logs -f green:latest
